### ISSUE TITLE
Add a page to the documentation of papers where adaptive is used

### ISSUE THREAD

**Issue by basnijholt** [python-adaptive/adaptive#163]
* https://arxiv.org/abs/1806.02801
* https://arxiv.org/abs/1807.01940
* https://arxiv.org/abs/1903.06168 and [code](https://zenodo.org/record/2578027)
* https://arxiv.org/abs/1903.02492

**Comment by akhmerov** [comment]
@adriaanrol is that right?

**Comment by AdriaanRol** [comment]
https://arxiv.org/abs/1903.02492

We use it to determine the points to sample in the simulations. We have also used it in the experiments but the data shown in the paper is measured using the conventional (grid like) data acquisition.
