### ISSUE TITLE
set python_requires in setup.py

### ISSUE THREAD

**Issue by Carreau** [python-adaptive/adaptive#179]
See https://python3statement.org/practicalities/

python_requires will tell to pip ahead of time not to even _try_ to install on incompatible versions. That will avoid error message on triggered by the test in here https://github.com/python-adaptive/adaptive/blob/master/setup.py#L8-L10. 

it's too late for already released versions, but at least for the newest ones you could set that up.

**Comment by basnijholt** [comment]
Thanks a lot! I've addressed this in https://github.com/python-adaptive/adaptive/pull/180.
