### ISSUE TITLE
jupyter-sphinx is pinned to non-existing branch

### ISSUE THREAD

**Issue by berceanu** [python-adaptive/adaptive#199]
https://github.com/python-adaptive/adaptive/blob/01e26ef69aaf249cfd386173c119d98b65d8c53d/docs/environment.yml#L16

**Comment by berceanu** [comment]
My bad, the branch does actually exist, on @basnijholt fork. Shouldn't https://github.com/jupyter-widgets/jupyter-sphinx.git be used instead?

**Comment by basnijholt** [comment]
Good point, but it should only work after the code of https://github.com/jupyter-widgets/jupyter-sphinx/pull/49 makes it into a release, which hasn't happened yet.

I will keep this issue open as a reminder to switch though :)

**Comment by basnijholt** [comment]
Closing in favor of https://github.com/python-adaptive/adaptive/issues/203.
