### ISSUE TITLE
Does not work with lambda functions

### ISSUE THREAD

**Issue by RafalSkolasinski** [python-adaptive/adaptive#206]
For example, if in the initial example one have
```
def g(x, offset=offset, wait=True):
    from time import sleep
    from random import random

    a = 0.01
    if wait:
        sleep(random() / 10)
    return x + a**2 / (a**2 + (x - offset)**2)


f = lambda x: g(x)
```
then execution just hangs.

**Comment by basnijholt** [comment]
Hi @RafalSkolasinski,

That is expected because the function needs to be pickled such that it can be send to the executor. Therefore lambda functions will never work with the default `ProcessPoolExecutor`.

**Comment by RafalSkolasinski** [comment]
That's a bummer. Any chance you could raise ValueError in such cases and produce a nice warning message?

**Comment by basnijholt** [comment]
That makes sense, @jbweston, would you know how to best tackle this?

**Comment by RafalSkolasinski** [comment]
Even better would be to find mechanism to make `lambda` expression pickable.

**Comment by basnijholt** [comment]
It's already possible with ipyparallel if you enable dill or cloudpickle.

**Comment by akhmerov** [comment]
@RafalSkolasinski can you please provide the complete code sample?

This likely depends on which runner you are using.

**Comment by basnijholt** [comment]
@jbweston it is not obvious that this blocks the kernel, but it does hang forever...

```python
import adaptive
adaptive.notebook_extension()

ring2 = lambda xy: xy[0]**2 + xy[1]**2
learner = adaptive.Learner2D(ring2, bounds=[(-1, 1), (-1, 1)])
runner = adaptive.Runner(learner, goal=lambda l: l.npoints >= 1000)
runner.live_info()
```
