### ISSUE TITLE
PyYAML yaml.load(input) Deprecation

### ISSUE THREAD

**Issue by jakepan1994** [python-adaptive/adaptive#207]
It seems that some packages are deprecated now, here is the warning I received:

 YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

**Comment by akhmerov** [comment]
Hm, I'm not sure where we're using `yaml`, can you provide the full traceback please?

**Comment by jakepan1994** [comment]
Okay, after update conda, it seems the warning goes away
