### ISSUE TITLE
release v0.9.0

### ISSUE THREAD

**Issue by basnijholt** [python-adaptive/adaptive#212]
Since [0.8.0](https://github.com/python-adaptive/adaptive/tree/v0.8.0) we fixed the following [issues](https://github.com/python-adaptive/adaptive/issues):

- [#217](https://github.com/python-adaptive/adaptive/issues/217) Command-line tool
- [#211](https://github.com/python-adaptive/adaptive/issues/211) Defining inside main() in multiprocess will report error
- [#208](https://github.com/python-adaptive/adaptive/issues/208) Inquiry on implementation of parallelism on the cluster
- [#207](https://github.com/python-adaptive/adaptive/issues/207) PyYAML yaml.load(input) Deprecation
- [#203](https://github.com/python-adaptive/adaptive/issues/203) jupyter-sphinx update Documentation enhancement
- [#199](https://github.com/python-adaptive/adaptive/issues/199) jupyter-sphinx is pinned to non-existing branch

and merged the following [Pull requests](https://github.com/python-adaptive/adaptive/pulls):
- [#219](https://github.com/python-adaptive/adaptive/pull/219) pass value_scale to the LearnerND's loss_per_simplex function
- [#209](https://github.com/python-adaptive/adaptive/pull/209) remove MPI4PY_MAX_WORKERS where it's not used
- [#204](https://github.com/python-adaptive/adaptive/pull/204) use jupyter_sphinx v0.2.0 from conda instead of my branch
- [#200](https://github.com/python-adaptive/adaptive/pull/200) ensure atomic writes when saving a file
- [#193](https://github.com/python-adaptive/adaptive/pull/193) Add a SequenceLearner
- [#188](https://github.com/python-adaptive/adaptive/pull/188) BalancingLearner: add a "cycle" strategy, sampling the learners one by one
- [#202](https://github.com/python-adaptive/adaptive/pull/202) Authors
- [#201](https://github.com/python-adaptive/adaptive/pull/201) Update tutorial.parallelism.rst
- [#197](https://github.com/python-adaptive/adaptive/pull/197) Add option to display a progress bar when loading a BalancingLearner
- [#195](https://github.com/python-adaptive/adaptive/pull/195) don't treat the no data case differently in the Learner1D  Learner1D
- [#194](https://github.com/python-adaptive/adaptive/pull/194) pin everything in the docs/environment.yml file

**Comment by likewei92** [comment]
It seems that 0.9.0 hasn't been pushed to pypi yet? When I import SequenceLearner from adaptive scheduler it is sleeping 10s and asking me to update to adaptive >=0.9.0, but I can't update that version yet?

**Comment by basnijholt** [comment]
Hi @likewei92, thanks for reminding me! I've just released [v0.9.0](https://github.com/python-adaptive/adaptive/releases/tag/v0.9.0).

It's on PyPI now and soon on conda-forge.
