### ISSUE TITLE
use tox for testing

### ISSUE THREAD

**Issue by jbweston** [python-adaptive/adaptive#238]
tox has a couple of benefits:

+ transparent testing against python/dependency version matrices
+ a single configuration file (many other tools in our testing pipeline e.g. flake8 read tox.ini)
+ can also build documentation, ensuring that the correct environment is used.

Check out https://github.com/jbweston/qsim/ to see how it looks.

**Comment by basnijholt** [comment]
That sounds like a good idea.

Will you open a PR?

**Comment by jbweston** [comment]
> That sounds like a good idea.
> 
> Will you open a PR?

Eventually, yes.

**Comment by basnijholt** [comment]
I've made a start in https://github.com/python-adaptive/adaptive/pull/247
