### ISSUE TITLE
Make Runner work with unhashable points

### ISSUE THREAD

**Issue by basnijholt** [python-adaptive/adaptive#267]
Currently `Runner`s do not support the points to be unhashable. This leads to https://github.com/python-adaptive/adaptive/issues/265.

Allowing the `Runner` to work with any points would simplify the `SequenceLearner` and means we wouldn't have to convert numpy arrays to tuples in all other learners.

**Comment by akhmerov** [comment]
> means we wouldn't have to convert numpy arrays to tuples in all other learners.

Not necessarily—the other learners might still rely on dictionaries for the internal data structure.

Still the runner doesn't really need to store a lot of state, and making its interface more general is an improvement.
