### ISSUE TITLE
GPU acceleration

### ISSUE THREAD

**Issue by rahimentezari** [python-adaptive/adaptive#296]
Is it possible to use GPU for speedup? I need to use adaptive.learner.triangulation

**Comment by akhmerov** [comment]
I don't think triangulation would benefit from GPU—it does random access on small chunks of data with a lot of reads and writes.

It would benefit from rewriting in a compiled language (or maybe using e.g. numba for jit): right now it's all Python code.

**Comment by jonas-eschle** [comment]
I agree, GPU on this level does not make sense. In general, vectorization of the problem is rather impossible because of the adaptive nature of the problem.

**Comment by akhmerov** [comment]
Closing as no action.
