### ISSUE TITLE
Emphasis on when to use adaptive in docs

### ISSUE THREAD

**Issue by thomasaarholt** [python-adaptive/adaptive#297]
Hiya,

Thanks for writing adaptive. I think it's a super cool algorithm, and it's incredibly accessible!
I've spent this afternoon playing around with it, and something that I wish was emphasized in the docs is _when_ to use adaptive:

    When evaluating a function on one point takes an appreciable amount of time!

(this is my take on it, at least - there are probably other aspects that I'm not considering)

For instance, the examples used for Learner1D and Learner2D, while very clear and informative, do give the impression that Adaptive would be useful for that "sized" problem. That is, evaluating something like:

```python
def peak(x, a=0.01):
    return x + a**2 / (a**2 + x**2)
```

Authors of the package might say "this is obviously not an appropriate problem for adaptive", since NumPy evaluation on an array is extremely fast (evaluating the above on `x = np.linspace(-1, 1, 100000)` takes about 100 us). However, nowhere in the docs is the above quote hinted at!

It seems that Adaptive really shines is on a problem where the computation of a single datapoint takes significantly longer than nanoseconds. Perhaps the authors have an idea of where the overhead of running Adaptive becomes insignificant compare to the benefits of an adaptive grid? (Milliseconds? Day?) Advertising where the package is particularly strong would probably get even more people excited about it!

I'm happy to submit a PR to the readme or docs, I just thought I'd emphasise it here first, in case the maintainers had any thoughts.

**Comment by basnijholt** [comment]
Hi @thomasaarholt, you are absolutely right!

It only makes sense to adaptively sample something whenever the function is sufficiently slow.

We are preparing a manuscript (https://github.com/python-adaptive/paper) where I wrote down some simple estimate:
![image](https://user-images.githubusercontent.com/6897215/102641269-1466a500-415c-11eb-9246-2224b5c38b80.png)


Typically, the function that is being evaluated should be slower than ≈100 ms to really benefit from running stuff with Adaptive.

**Comment by basnijholt** [comment]
> It seems that Adaptive really shines is on a problem where the computation of a single datapoint takes significantly longer than nanoseconds. Perhaps the authors have an idea of where the overhead of running Adaptive becomes insignificant compare to the benefits of an adaptive grid? (Milliseconds? Day?) Advertising where the package is particularly strong would probably get even more people excited about it!
> I'm happy to submit a PR to the readme or docs, I just thought I'd emphasise it here first, in case the maintainers had any thoughts.

Indeed, you are correct, we do not clearly write this in the docs. Any contributions in the form of a PR is always welcome! :heart:
