### ISSUE TITLE
Runner fails in the notebook

### ISSUE THREAD

**Issue by ncuxomun** [python-adaptive/adaptive#299]
Hi.

Thank you very much for sharing your project! 

I have attempted to run some tutorials on my machine(s), OS: Windows 10 | Python 3.8.5, but the runner fails to execute. For example:
![image](https://user-images.githubusercontent.com/54369128/109054190-71b62f80-7692-11eb-90fd-55ae9bc3d2be.png).

Please note that when I tried running the examples on Binder, everything worked smoothly. Can you please help me resolve the issue because I would like to run a set of my experiments?

Thank you very much for your attention!

**Comment by basnijholt** [comment]
Could you try runner.task.print_stack() to see the error.

**Comment by basnijholt** [comment]
Also see https://adaptive.readthedocs.io/en/latest/tutorial/tutorial.advanced-topics.html#debugging-problems

**Comment by ncuxomun** [comment]
> Could you try runner.task.print_stack() to see the error.

Hi, Bas. May I call you by your name?
Thanks for responding. Here is the error:
![image](https://user-images.githubusercontent.com/54369128/109063512-125e1c80-769e-11eb-86ad-c6fbb82dcdfe.png)

**Comment by basnijholt** [comment]
I think you are just missing the relevant bit of the error message here.

**Comment by ncuxomun** [comment]
I screen'ed entire message in the notebook. How can I find the relevant bit?

**Comment by basnijholt** [comment]
The part that comes after the raise RuntimeError on the last line.

**Comment by ncuxomun** [comment]
I ran the script version, and the error message is:
![image](https://user-images.githubusercontent.com/54369128/109064430-4259ef80-769f-11eb-9333-352e7cdbbb6b.png)

**Comment by ncuxomun** [comment]
![image](https://user-images.githubusercontent.com/54369128/109064806-b3010c00-769f-11eb-8a6f-f5531a286bb3.png)

**Comment by basnijholt** [comment]
Could you try
```
pip install loky
```
and try again?

**Comment by ncuxomun** [comment]
Hello!
Thank you so much for the suggestion - it worked! But I could not plot the figure as shown below:
![image](https://user-images.githubusercontent.com/54369128/109363522-a1f00080-7841-11eb-8b9e-692e7287aab5.png)
I did not observe the plotting issue when I was facing the previous issue.

**Comment by basnijholt** [comment]
What version holoviews do you have installed?

**Comment by ncuxomun** [comment]
It is holoviews 1.14.1, the version that is requested and installed when installing adaptive.

**Comment by basnijholt** [comment]
I can reproduce it after upgrading bokeh from 2.2.3 to 2.3.0.

I will come up with a fix.

**Comment by basnijholt** [comment]
This is this issue https://github.com/holoviz/holoviews/issues/4848. HoloViews folks plan to have a release in the next few days. 

In the meantime, you can fix it by doing
```
pip install -U bokeh=2.2.3
```

**Comment by ncuxomun** [comment]
Thanks a lot! I think I should be good to start exploring the package.
