### ISSUE TITLE
Warning when importing adaptive

### ISSUE THREAD

**Issue by peendebak** [python-adaptive/adaptive#321]
When importing `adaptive` I get the following warning:

![image](https://user-images.githubusercontent.com/17724047/119971216-f7f35200-bfb0-11eb-8f50-24dfe35c4aa9.png)

**Comment by akhmerov** [comment]
It's a warning about windows converting the line endings of a file which isn't a part of the adaptive (package), but which is provided in the repository. As such it isn't important, however I am surprised that this warning appears on importing adaptive.

Does the same warning appear if you just execute `python -c "print('hello')"` within the same folder?

**Comment by eendebakpt** [comment]
@akhmerov It is somehow related to `adaptive` being imported. I have it installed with `pip install -e .`.

![image](https://user-images.githubusercontent.com/883786/120478245-ef35be00-c3ac-11eb-84bf-429730764469.png)

**Comment by peendebak** [comment]
The warning seems related to git, although why it is triggered when executing python I do not understand. On a new install I cannot reproduce this warning. So I will close the issue
