### ISSUE TITLE
Is it possible to pass args and kwargs to sampled function?

### ISSUE THREAD

**Issue by MarkusSchwarz1980** [python-adaptive/adaptive#337]
The function that I want to sample takes several arguments and keyword arguments, but `Learner1D` only works with a function of one argument. I want to pass args and kwargs to the sampled function, i.e. I want something like this to work
```python
def f_arg(x, a, offset=offset, wait=True):
    from time import sleep
    from random import random

    if wait:
        sleep(random() / 100)
    return x + a**2 / (a**2 + (x - offset)**2)

my_a = 0.1
my_offset = 0.0
curvature_loss = curvature_loss_function()
learner = adaptive.Learner1D(f_arg, (-1, 1), curvature_loss, my_a, offset=my_offset)
```
My current solution is to modify the `__init__` of `Learner1D` as
```python
    def __init__(
        self,
        function: Callable[[Real], Union[Float, np.ndarray]],
        bounds: Tuple[Real, Real],
        loss_per_interval: Optional[Callable[[XsTypeN, YsTypeN], Float]] = None,
        *args, **kwargs
    ):
        self.function_args = args
        self.function_kwargs = kwargs
```
and then modify `_submit()`  of `BlockingRunner` as
```python
    def _submit(self, x):
        return self.executor.submit(self.learner.function, x,
                                    *self.learner.function_args,
                                    **self.learner.function_kwargs)

```
This works for my current case, but I don't know if it would break code elsewhere.

**Comment by akhmerov** [comment]
Wouldn't [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial) be a standard way to address this problem?

**Comment by MarkusSchwarz1980** [comment]
> Wouldn't [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial) be a standard way to address this problem?

This would only partially solve the problem (pun intended), since only the leftmost positional arguments get 'frozen'. So using `f_wrapper = functools.partial(f_arg, my_a, offset=my_offset)` and calling `f_wrapper(-0.1)` results in `0.6` instead of the expected `0.4`, since the positional arguments `x`, and `a` get swapped.

However, it works with a slight modification given in the documentation of [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial) by defining
```python
def wrapper(func, *args, **keywords):
    @functools.wraps(func)
    def newfunc(x, *fargs, **fkeywords):
        newkeywords = {**keywords, **fkeywords}
        return func(x, *args, *fargs, **newkeywords)
    newfunc.func = func
    newfunc.args = args
    newfunc.keywords = keywords
    return newfunc
```
Using `f_wrapper = wrapper(f_arg, my_a, offset=my_offset)` and calling `f_wrapper(-0.1)` gives the expected result of `0.4`. The function `f_wrapper` then also works with `Learner1D`.

**Comment by akhmerov** [comment]
You can also provide the arguments via keywords in `functools.partial`. Either way, wrapping the function is, I think, the most appropriate solution for handling functions with extra arguments, and therefore I'm closing the issue. Do feel free to reopen if you can think of an improvement, or if you think there are other aspects that this approach doesn't address in a satisfactory manner.
