### ISSUE TITLE
Wrong sign for right boundary with Sympy

### ISSUE THREAD

**Issue by Davide-sd** [python-adaptive/adaptive#338]
Let's consider the following simple example. First, I'm going to show the correct result when using Numpy:

```python
import numpy as np
from adaptive import notebook_extension, Learner1D
from adaptive.runner import simple
import dill

notebook_extension()

def func(x):
    return np.imag(np.sqrt(-(x + 0j)))

def goal(learner):
    return learner.loss() < 0.1

learner = Learner1D(func, bounds=(-1, 1))
simple(learner, goal)
learner.plot()
```
![bokeh_plot](https://user-images.githubusercontent.com/9921777/145424941-8cd48c55-912b-4afe-bdcf-7e34924bae14.png)

Now, I'm going to use Sympy to generate a function which is going to be evaluated with Numpy:

```python
from sympy import *
var("x")
f = im(sqrt(-x))

# func is going to use Numpy
func = lambdify(x, f)

def goal(learner):
    return learner.loss() < 0.1

learner = Learner1D(func, bounds=(-1, 1))
learner_bytes = dill.dumps(learner)
learner_loaded = dill.loads(learner_bytes)
simple(learner_loaded, goal)
learner_loaded.plot()
```
![bokeh_plot(1)](https://user-images.githubusercontent.com/9921777/145425090-e2755f3e-beb4-495c-b948-bcacc761a888.png)

As you can see, the last evaluation point (the right boundary) has the wrong sign. Even if I change the boundaries, the last point will always have the wrong sign. Why does it happen? Is it something that I can fix with some option in the learner/runner or is it an internal bug?

**Comment by basnijholt** [comment]
Thanks for reporting!

That looks like a bug, I will try to look into it today or tomorrow.

**Comment by basnijholt** [comment]
It seems like it is a problem purely on SymPy's side:
```python
from sympy import im, sqrt, lambdify, var
var("x")
f = im(sqrt(-x))
func = lambdify(x, f)
print(func(1))
```
prints:
`>>> 1`

**Comment by Davide-sd** [comment]
Interesting, Numpy deals with (complex number) branch cuts differently depending on the input data type. For example `f_numpy(1), f_numpy(1.0)` outputs `(1.0, -1.0)`. It appears that there is no bug with adaptive. Thanks for pointing me in the right direction. All I need to do is to use float boundaries. I'm closing the issue.
