### ISSUE TITLE
Stop using atomic writes

### ISSUE THREAD

**Issue by akhmerov** [python-adaptive/adaptive#352]
[atomicwrites is now deprecated](https://github.com/untitaker/python-atomicwrites#unmaintained) and recommends using `os.replace` instead. pytest used pytest-dev/pytest#10115 to make a replacement. While I don't expect that things would break on a short notice, we should consider stopping to rely on atomicwrites.

**Comment by basnijholt** [comment]
Well caught. I'll fix this on a slow day.

**Comment by basnijholt** [comment]
Fixed by #353 🎉
