### ISSUE TITLE
Documentation: use cases of coroutine by Learner and Runner not properly explained

### ISSUE THREAD

**Issue by juandaanieel** [python-adaptive/adaptive#360]
[AsyncRunner](https://adaptive.readthedocs.io/en/latest/_modules/adaptive/runner.html#AsyncRunner) checks if the function to be learned is a coroutine or not. This function comes from the learner, e.g. [BaseLearner](https://adaptive.readthedocs.io/en/latest/reference/adaptive.learner.base_learner.html) which says that the function might be modified by a subclass but gives no information about when or about it being a coroutine.

Documentation could be more explicit about:
- Learners accepting coroutines as functions. This is currently only mentioned in the runner's documentation.
- Mention in what cases the function is modified by the subclass of BaseLearner.

**Comment by basnijholt** [comment]
I believe this can be closed right?

**Comment by akhmerov** [comment]
Yep, #364 closes this.
