### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by basnijholt** [python-adaptive/adaptive#368]
This change is very easy (https://github.com/github/renaming).

Any objections @jbweston or @akhmerov?

**Comment by akhmerov** [comment]
I'm OK with that.

**Comment by jbweston** [comment]
I am fine also

**Comment by basnijholt** [comment]
Great! I have just made the change.

As GitHub will tell you.

If you have a local clone, you can update it by running the following commands.
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
