### ISSUE TITLE
No module named 'typing_extensions'"

### ISSUE THREAD

**Issue by Davide-sd** [python-adaptive/adaptive#394]
[It appears](https://stackoverflow.com/questions/74903914/sympy-plotting-backends-library-unable-to-save-plot-in-svg-format) that for Python < 3.10 the `typing_extension` module is required, but it is not installed by `adaptive`. Is it possible to add some conditional setup to get it installed automatically?

 Edit: I've seen the condition on `setup.py`...

**Comment by basnijholt** [comment]
It should install it:

https://github.com/python-adaptive/adaptive/blob/b24b64411579f33f70c68feab0d4e8563db1c8d4/setup.py#L35

I’m currently AFK until January 3rd so cannot debug this. I could accept a PR though.

**Comment by Davide-sd** [comment]
Couldn't replicate the issue. I'm going to close this.
