### ISSUE TITLE
Use in script with BlockingRunner: get log and/or feedback on progress

### ISSUE THREAD

**Issue by bonh** [python-adaptive/adaptive#436]
In a notebook, I can use `live_info()` to display the progress. Is something similar available if I run `adaptive` in a script?

**Comment by basnijholt** [comment]
@bonh, that is currently not available, however, I just opened https://github.com/python-adaptive/adaptive/pull/441 to add this.

You can use it like:


```python
runner = adaptive.Runner(learner, loss_goal=0.01)

async def run(runner, fname: str):
    runner.live_info_terminal()
    await runner.task
    runner.learner.save(fname)

asyncio.run(run(learner, "learner.pkl"))
```

**Comment by basnijholt** [comment]
![Screen Recording 2023-08-20 at 1 19 30 PM](https://github.com/python-adaptive/adaptive/assets/6897215/c1cf3e39-af86-4bc0-97d2-6a6be82001d0)

**Comment by bonh** [comment]
Sry, I got distracted. Thanks for the suggestion! I hope to try it soon.

**Comment by bonh** [comment]
perfect, thanks!
