### ISSUE TITLE
Handling with regions unreachable inside the `ConvexHull` in `LearnerND`

### ISSUE THREAD

**Issue by lsyxiaopang** [python-adaptive/adaptive#438]
This library is very cool and I've been using it for controlling measuring instruments. However, for measuring instruments, there would be some situations where **one or more regions inside the range cannot reach**, and the parameters of `LearnerND` cannot handle this problem.

So, is there any ways to solve this problem without affecting the library too much, for example, if I got point that I can't reach, I may just return 0.

Thank you!

**Comment by basnijholt** [comment]
If you know these unreachable regions before hand, you could write a WrappedFunction around the function that controls your instrument. Then, if you are within those regions, you will simply return NaN.

**Comment by lsyxiaopang** [comment]
> If you know these unreachable regions before hand, you could write a WrappedFunction around the function that controls your instrument. Then, if you are within those regions, you will simply return NaN.

Thank you, I think these NaNs may not affect the predictions too much.
