### ISSUE TITLE
Create API for just signle process (No pickle)

### ISSUE THREAD

**Issue by lsyxiaopang** [python-adaptive/adaptive#442]
I am trying to combine adaptive and mph (a python interface to interact with COMSOL) together, but I've found that when I try to make a runner, it will tell me `TypeError: cannot pickle '_jpype._JField' object` 

I only need one process (because `mph` only supports it), so I think pickle may not needed. Is there any method that can avoid pickle? 

Thank you

**Comment by basnijholt** [comment]
Try https://adaptive.readthedocs.io/en/latest/reference/adaptive.runner.extras.html#adaptive.runner.simple


Also, could you share your code (i.e., what have you tried exactly?)

**Comment by lsyxiaopang** [comment]
> Try https://adaptive.readthedocs.io/en/latest/reference/adaptive.runner.extras.html#adaptive.runner.simple
> 
> Also, could you share your code (i.e., what have you tried exactly?)

Thank you, it works! What a shame that I didn't fully read the document
